name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        python build_with_version.py
        
    - name: Get App Version
      run: |
        $version = Select-String -Path Bldbuy_Recon_UI.py -Pattern "VERSION = '([\d\.]+)'" | ForEach-Object { $_.Matches.Groups[1].Value }
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV
        
    - name: Create ZIP Archive
      run: |
        Compress-Archive -Path dist/recon_tools_*.exe -DestinationPath dist/recon_tools_v${{ env.APP_VERSION }}.zip -Force

    - name: Upload to DUFS
      run: |
        $file = Get-ChildItem dist/recon_tools_*.zip | Select-Object -First 1
        curl -T $file.FullName -u fujiwen:Hilton1@# https://down.hksft.com/upload/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: recon_tools_v${{ env.APP_VERSION }}
        path: dist/recon_tools_*.exe
